---
- hosts: ec2_instances
  become: true
  tasks:
    - name: update apt
      apt:
        update_cache: yes

    - name: Install Docker Dependencies
      apt:
        name:
          - docker.io
          - python3-pip

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present
        executable: pip3

    - name: Clone api repo
      git:
        repo: https://github.com/Ihssaneabousshal/hotelreservationapi.git
        dest: /hotelreservationapi
        force: yes

    - name: delete containers
      command: docker-compose down --volumes --rmi all
      args:
        chdir: /hotelreservationapi

    - name: run dockers
      command: docker-compose up -d
      args:
        chdir: /hotelreservationapi
